name: Create Release with PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Generate PDF
        run: |
          npx md-to-pdf resume.md --config-file .md-to-pdf.json --document-title "職務経歴書"

      - name: Upload PDF as artifact
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: resume-pdf
          path: resume.pdf

      - name: Generate version tag
        if: github.ref == 'refs/heads/main'
        id: version
        run: |
          VERSION=$(date +'%Y.%m.%d')-${{ github.run_number }}
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          files: resume.pdf
          generate_release_notes: true
