name: Create Release with PDF

on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Generate PDF
        run: |
          npx md-to-pdf resume.md --config-file .md-to-pdf.json

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: resume.pdf
          generate_release_notes: true
